version: '3'

volumes:
  dbconfig:
  dblog:
  dbdata:

services:
  db:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - "dbconfig:/etc/postgresql"
      - "dblog:/var/log/postgresql"
      - "dbdata:/var/lib/postgresql"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
  server:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
