version: '3'

volumes:
  dbconfigfb:
  dblogfb:
  dbdatafb:
  mvncachefb:

services:
  db:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - "dbconfigfb:/etc/postgresql"
      - "dblogfb:/var/log/postgresql"
      - "dbdatafb:/var/lib/postgresql"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
  server:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - "mvncachefb:/root/.m2"
    depends_on:
      - db
