version: '3'

services:
  db:
    image: postgres:9.6.5
    ports:
      - "5432:5432"
    volumes:
      - /etc/postgresql
      - /var/log/postgresql
      - /var/lib/postgresql
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
  server:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
